import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { defaultBusinesses } from '../src/data/defaultBusinesses';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function sqlString(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

const cols =
  '(id, name, category, description, address, phone, website, city, cnic, status, created_at)';

const values = defaultBusinesses
  .map(
    (b) =>
      `(${sqlString(b.id)}, ${sqlString(b.name)}, ${sqlString(b.category)}, ${sqlString(b.description)}, ${sqlString(b.address)}, ${sqlString(b.phone)}, ${sqlString(b.website)}, ${sqlString(b.city)}, ${sqlString(b.cnic)}, ${sqlString(b.status)}, ${sqlString(b.createdAt)}::timestamptz)`
  )
  .join(',\n');

const out = `-- Generated by scripts/generate-seed.ts — run after migration in Supabase SQL Editor (or psql)
INSERT INTO public.businesses ${cols}
VALUES
${values}
ON CONFLICT (id) DO NOTHING;
`;

const target = path.join(__dirname, '..', 'supabase', 'seed.sql');
writeFileSync(target, out, 'utf8');
console.log('Wrote', target);
